### ISSUE TITLE
bad code snippet

### ISSUE THREAD

**Issue by waigani** [codelingo/docs#70]
`query` should be indented https://www.codelingo.io/docs/concepts/tenets/:

```
tenets:
  - name: find-funcs
    doc: "example Tenet that finds all func decls"
    flows:
      codelingo/review:
        comment: "this is a function"

query:
  import go

  @review.comment
  go.func_decl
```
